"""Generate supplementary LaTeX tables for P1/P3/P4/P5 results."""
import os, json, argparse
import numpy as np

CATS = ["Video_Games", "Baby_Products", "Toys_and_Games"]
DS = {"Video_Games": "Video Games", "Baby_Products": "Baby Products",
      "Toys_and_Games": "Toys \\& Games"}


def agg(runs, prefix, seeds, path):
    vals = []
    for s in seeds:
        p = os.path.join(runs, f"{prefix}_s{s}", "metrics.json")
        if not os.path.exists(p):
            continue
        d = json.load(open(p, encoding="utf-8"))
        cur = d
        for k in path:
            cur = cur[k]
        vals.append(cur)
    if not vals:
        return None
    m = np.mean(vals)
    sd = np.std(vals, ddof=1) if len(vals) > 1 else 0.0
    return m, sd, len(vals)


def cell(runs, prefix, seeds, path):
    a = agg(runs, prefix, seeds, path)
    if a is None:
        return "--"
    return f"{a[0]:.4f}$\\pm${a[1]:.4f}"


def table_learned(runs, out):
    s5 = (2026, 2027, 2028, 2029, 2030)
    rows = [
        ("CSA-Rec (ours)", "full"),
        ("Content-kNN", "contentknn"),
        ("CLCRec", "clcrec"),
        ("Content2Emb", "content2emb"),
        ("DropoutNet", "dropoutnet"),
        ("LightGCN (CF only)", "ctrlcf"),
    ]
    lines = [
        "% auto-generated by scripts/make_extra_tables.py",
        "\\begin{table*}[!t]",
        "\\centering",
        "\\caption{Learned and training-free cold-start baselines at $K=20$ "
        "(mean $\\pm$ std; five seeds for CSA-Rec, content-kNN, and the learned heads; "
        "three seeds for the CF backbone). Cold items are ranked within the cold pool. "
        "Best per column in \\textbf{bold}.}",
        "\\label{tab:learned}",
        "\\small",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Method & Video Games & Baby Products & Toys \\& Games \\\\",
        "\\midrule",
    ]
    best = {c: -1 for c in CATS}
    data = {}
    for name, m in rows:
        data[name] = {}
        for c in CATS:
            seeds = s5 if m != "ctrlcf" else (2026, 2027, 2028)
            v = agg(runs, f"{c}_{m}", seeds, ("metrics", "cold", "recall@20"))
            data[name][c] = v
            if v and v[0] > best[c]:
                best[c] = v[0]
    for name, m in rows:
        cells = []
        for c in CATS:
            v = data[name][c]
            if v is None:
                cells.append("--")
            else:
                txt = f"{v[0]:.4f}$\\pm${v[1]:.4f}"
                if abs(v[0] - best[c]) < 1e-9:
                    txt = f"\\textbf{{{txt}}}"
                cells.append(txt)
        lines.append(f"{name} & {' & '.join(cells)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    path = os.path.join(out, "tables", "table_learned.tex")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write("\n".join(lines))
    print(f"[saved] {path}")


def table_temporal(runs, out):
    s3 = (2026, 2027, 2028)
    methods = [
        ("Content-kNN", "contentknn_temporal"),
        ("LightGCN (CF only)", "ctrlcf_temporal"),
        ("CSA-Rec (ours)", "full_temporal"),
    ]
    lines = [
        "% auto-generated by scripts/make_extra_tables.py",
        "\\begin{table}[!t]",
        "\\caption{Cold ranking under a temporal (newest-item) cold-start split "
        "(mean $\\pm$ std over three seeds). The newest 10\\% of items by first "
        "appearance are held out; all other settings match Table~\\ref{tab:main}. "
        "Best per block in \\textbf{bold}.}",
        "\\label{tab:temporal}",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Method & Cold R@20 & Cold N@20 \\\\",
        "\\midrule",
    ]
    for c in CATS:
        lines.append(f"\\multicolumn{{3}}{{l}}{{\\emph{{{DS[c]}}}}} \\\\")
        best_r = best_n = -1
        vals = {}
        for name, m in methods:
            r = agg(runs, f"{c}_{m}", s3, ("metrics", "cold", "recall@20"))
            n = agg(runs, f"{c}_{m}", s3, ("metrics", "cold", "ndcg@20"))
            vals[(name, m)] = (r, n)
            if r and r[0] > best_r:
                best_r = r[0]
            if n and n[0] > best_n:
                best_n = n[0]
        for name, m in methods:
            r, n = vals[(name, m)]
            rc = f"{r[0]:.4f}$\\pm${r[1]:.4f}" if r else "--"
            nc = f"{n[0]:.4f}$\\pm${n[1]:.4f}" if n else "--"
            if r and abs(r[0] - best_r) < 1e-9:
                rc = f"\\textbf{{{rc}}}"
            if n and abs(n[0] - best_n) < 1e-9:
                nc = f"\\textbf{{{nc}}}"
            lines.append(f"\\;{name} & {rc} & {nc} \\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\end{table}", ""]
    path = os.path.join(out, "tables", "table_temporal.tex")
    open(path, "w", encoding="utf-8").write("\n".join(lines))
    print(f"[saved] {path}")


def table_encoder(runs, out):
    configs = [
        ("Content-kNN", "contentknn", "", (2026, 2027, 2028, 2029, 2030)),
        ("Content-kNN", "contentknn", "_mpnet", (2026, 2027, 2028)),
        ("CSA-Rec", "full", "", (2026, 2027, 2028, 2029, 2030)),
        ("CSA-Rec", "full", "_mpnet", (2026, 2027, 2028)),
    ]
    lines = [
        "% auto-generated by scripts/make_extra_tables.py",
        "\\begin{table}[!t]",
        "\\caption{Encoder-scaling study: cold Recall@20 with a compact 384-d encoder "
        "(MiniLM, the default) versus a stronger 768-d encoder (MPNet), all else fixed. "
        "CSA-Rec and content-kNN use five seeds (MiniLM) / three seeds (MPNet).}",
        "\\label{tab:encoder}",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "Method & Encoder & Video Games & Baby & Toys \\\\",
        "\\midrule",
    ]
    for i, (name, base, suffix, seeds) in enumerate(configs):
        enc = "MiniLM-384" if suffix == "" else "MPNet-768"
        cells = []
        for c in CATS:
            a = agg(runs, f"{c}_{base}{suffix}", seeds, ("metrics", "cold", "recall@20"))
            val = f"{a[0]:.4f}" if a else "--"
            if name == "CSA-Rec" and suffix == "_mpnet":
                val = f"\\textbf{{{val}}}"
            cells.append(val)
        lines.append(f"{name} & {enc} & {' & '.join(cells)} \\\\")
        if i == 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    path = os.path.join(out, "tables", "table_encoder.tex")
    open(path, "w", encoding="utf-8").write("\n".join(lines))
    print(f"[saved] {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="paper_assets")
    args = ap.parse_args()
    table_learned(args.runs, args.out)
    table_temporal(args.runs, args.out)
    table_encoder(args.runs, args.out)


if __name__ == "__main__":
    main()
