"""Significance testing + confidence intervals for the main comparison.

Reads runs/*/metrics.json, groups per (dataset, config) across seeds, and for
the headline cold-start metric reports:
  * mean, std, and a t-based 95% confidence interval half-width;
  * a paired t-test (and Wilcoxon when n is large enough) of CSA-Rec (full)
    against each competitor, pairing by seed (each seed redraws the split, so
    pairs are matched replications).

Runs locally on the synced ``runs/`` folder (needs numpy + scipy only).

Usage:
  python scripts/stats.py --runs ./runs --metric cold/recall@20
  python scripts/stats.py --runs ./runs --out paper_assets/significance.tex
"""
import os
import re
import glob
import json
import argparse
from collections import defaultdict

import numpy as np
from scipy import stats


DATASETS = ["Video_Games", "Baby_Products", "Toys_and_Games"]
# configs to test against the proposed full model, in report order
COMPETITORS = ["contentknn", "content2emb", "dropoutnet", "clcrec",
               "ctrlcf", "nocsia", "nocpg", "nofusion"]
PRETTY = {
    "full": "CSA-Rec (full)", "contentknn": "Content-kNN",
    "content2emb": "Content2Emb", "dropoutnet": "DropoutNet", "clcrec": "CLCRec",
    "ctrlcf": "LightGCN (CF)", "nocsia": "w/o CSIA", "nocpg": "w/o CPG",
    "nofusion": "w/o Fusion",
}


def parse_tag(tag):
    """Split a run tag into (dataset, config, seed)."""
    m = re.search(r"_s(\d+)$", tag)
    seed = int(m.group(1)) if m else None
    base = re.sub(r"_s\d+$", "", tag)
    for ds in DATASETS:
        if base == ds or base.startswith(ds + "_"):
            cfg = base[len(ds):].lstrip("_") or "full"
            return ds, cfg, seed
    return None, None, seed


def load(runs_dir, metric):
    split, key = metric.split("/")
    vals = defaultdict(dict)  # (ds, cfg) -> {seed: value}
    for path in glob.glob(os.path.join(runs_dir, "*", "metrics.json")):
        tag = os.path.basename(os.path.dirname(path))
        ds, cfg, seed = parse_tag(tag)
        if ds is None or seed is None:
            continue
        try:
            with open(path, encoding="utf-8") as f:
                m = json.load(f)
            v = m.get("metrics", {}).get(split, {}).get(key)
        except Exception:
            v = None
        if v is not None:
            vals[(ds, cfg)][seed] = float(v)
    return vals


def ci95(arr):
    n = len(arr)
    m = float(np.mean(arr))
    if n < 2:
        return m, 0.0, 0.0
    sd = float(np.std(arr, ddof=1))
    half = float(stats.t.ppf(0.975, n - 1) * sd / np.sqrt(n))
    return m, sd, half


def stars(p):
    if p is None:
        return ""
    return "***" if p < 1e-3 else "**" if p < 1e-2 else "*" if p < 5e-2 else "n.s."


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="./runs")
    ap.add_argument("--metric", default="cold/recall@20")
    ap.add_argument("--out", default="paper_assets/significance.tex")
    args = ap.parse_args()

    vals = load(args.runs, args.metric)
    if not vals:
        print(f"no runs parsed under {args.runs}")
        return

    print(f"\n=== {args.metric}: mean +/- 95% CI (n seeds), paired test vs CSA-Rec(full) ===")
    latex = [
        r"% auto-generated by scripts/stats.py",
        r"\begin{table}[!t]", r"\centering",
        r"\caption{Cold-start Recall@20 with 95\% confidence intervals over "
        r"random seeds, and paired $t$-tests of CSA-Rec against each competitor "
        r"($^{*}p<0.05$, $^{**}p<0.01$, $^{***}p<0.001$; n.s.\ = not significant). "
        r"Each seed redraws the cold split, so seeds are matched replications.}",
        r"\label{tab:significance}", r"\small", r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{ll ccc}", r"\toprule",
        r"Dataset & Method & Mean$\pm$CI & $\Delta$ vs full & $p$ \\", r"\midrule",
    ]

    for ds in DATASETS:
        full = vals.get((ds, "full"), {})
        if not full:
            continue
        seeds_full = sorted(full)
        fm, fsd, fci = ci95([full[s] for s in seeds_full])
        latex.append(r"\multirow{%d}{*}{%s}" % (1 + len(COMPETITORS),
                                                ds.replace("_", " ")))
        latex.append(f" & {PRETTY['full']} & {fm:.4f}$\\pm${fci:.4f} & -- & -- \\\\")
        print(f"\n[{ds}] {PRETTY['full']:16} {fm:.4f} +/- {fci:.4f} (n={len(seeds_full)})")
        for cfg in COMPETITORS:
            d = vals.get((ds, cfg), {})
            if not d:
                continue
            seeds = sorted(d)
            m, sd, ci = ci95([d[s] for s in seeds])
            common = [s for s in seeds_full if s in d]
            p = None
            if len(common) >= 2:
                a = np.array([full[s] for s in common])
                b = np.array([d[s] for s in common])
                if np.allclose(a - b, 0):
                    p = 1.0
                else:
                    p = float(stats.ttest_rel(a, b).pvalue)
            delta = fm - m
            print(f"       {PRETTY.get(cfg, cfg):16} {m:.4f} +/- {ci:.4f} "
                  f"| d={delta:+.4f} | p={p if p is None else round(p,4)} {stars(p)}")
            latex.append(f" & {PRETTY.get(cfg, cfg)} & {m:.4f}$\\pm${ci:.4f} & "
                         f"{delta:+.4f} & {stars(p)} \\\\")
        latex.append(r"\midrule")
    if latex[-1] == r"\midrule":
        latex[-1] = r"\bottomrule"
    else:
        latex.append(r"\bottomrule")
    latex += [r"\end{tabular}", r"\end{table}", ""]

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(latex))
    print(f"\n[saved] {args.out}")


if __name__ == "__main__":
    main()
